# -*- coding: utf-8 -*-
"""Analiza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JvMRRkEhHhGaTLii3HY_k9FIiKSDCJMC

#Instalacja i import potrzebnych pakietów
"""

import warnings
warnings.filterwarnings('ignore')

!pip install scikit-tda
!pip install Cython
!pip install Ripser
!pip install persim
!pip install teaspoon

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import ripser
import persim

from sklearn import datasets
from ripser import ripser
from persim import plot_diagrams
from ripser import Rips

import teaspoon.MakeData.PointCloud as makePtCloud
import teaspoon.TDA.Draw as Draw

allteams = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/AllTeams.csv')

pd.set_option('display.max_columns', None)

"""#MCI - Manchester City - 1"""

mci = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/MCI.csv')
mci

arrayPoints = np.array(mci[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgMCI = ripser(arrayPoints)['dgms']
plot_diagrams(dgMCI, show=True, xy_range=[-100,1200,-100,1200])

"""# LIV - Liverpool - 2"""

liv = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/LIV.csv') 
liv

arrayPoints = np.array(liv[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgLIV = ripser(arrayPoints)['dgms']
plot_diagrams(dgLIV, show=True, xy_range=[-100,1200,-100,1200])

"""#CHE - Chelsea - 3"""

che = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/CHE.csv') 
che

arrayPoints = np.array(che[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgCHE = ripser(arrayPoints)['dgms']
plot_diagrams(dgCHE, show=True, xy_range=[-100,1200,-100,1200])

"""#TOT - Tottenham Hotspur - 4"""

tot = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/TOT.csv') 
tot

arrayPoints = np.array(tot[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgTOT = ripser(arrayPoints)['dgms']
plot_diagrams(dgTOT, show=True, xy_range=[-100,1200,-100,1200])

"""#ARS - Arsenal - 5"""

ars = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/ARS.csv')
ars

arrayPoints = np.array(ars[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgARS = ripser(arrayPoints)['dgms']
plot_diagrams(dgARS, show=True, xy_range=[-100,1200,-100,1200])

"""#MUN - Manchester United - 6"""

mun = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/MUN.csv') 
mun

arrayPoints = np.array(mun[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgMUN = ripser(arrayPoints)['dgms']
plot_diagrams(dgMUN, show=True, xy_range=[-100,1200,-100,1200])

"""#WHU - West Ham United - 7"""

whu = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/WHU.csv') 
whu

arrayPoints = np.array(whu[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgWHU = ripser(arrayPoints)['dgms']
plot_diagrams(dgWHU, show=True, xy_range=[-100,1200,-100,1200])

"""#LEI - Leicester City - 8"""

lei = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/LEI.csv') 
lei

arrayPoints = np.array(lei[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgLEI = ripser(arrayPoints)['dgms']
plot_diagrams(dgLEI, show=True, xy_range=[-100,1200,-100,1200])

"""#BHA -	Brighton & Hove Albion - 9"""

bha = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/BHA.csv') 
bha

arrayPoints = np.array(bha[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgBHA = ripser(arrayPoints)['dgms']
plot_diagrams(dgBHA, show=True, xy_range=[-100,1200,-100,1200])

"""#WOL - Wolverhampton Wanderers - 10"""

wol = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/WOL.csv') 
wol

arrayPoints = np.array(wol[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgWOL = ripser(arrayPoints)['dgms']
plot_diagrams(dgWOL, show=True, xy_range=[-100,1200,-100,1200])

"""# NEW - Newcastle United - 11"""

new = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/NEW.csv') 
new

arrayPoints = np.array(new[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgNEW = ripser(arrayPoints)['dgms']
plot_diagrams(dgNEW, show=True, xy_range=[-100,1200,-100,1200])

"""# CRY -	Crystal Palace	- 12"""

cry = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/CRY.csv')
cry

arrayPoints = np.array(cry[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgCRY = ripser(arrayPoints)['dgms']
plot_diagrams(dgCRY, show=True, xy_range=[-100,1200,-100,1200])

"""#BRE - Brentford - 13"""

bre = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/BRE.csv')
bre

arrayPoints = np.array(bre[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgBRE = ripser(arrayPoints)['dgms']
plot_diagrams(dgBRE, show=True, xy_range=[-100,1200,-100,1200])

"""#AVL - Aston Villa - 14

"""

avl = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/AVL.csv')
avl

arrayPoints = np.array(avl[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgAVL = ripser(arrayPoints)['dgms']
plot_diagrams(dgAVL, show=True, xy_range=[-100,1200,-100,1200])

"""#SOU - Southampton - 15"""

sou = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/SOU.csv')
sou

arrayPoints = np.array(sou[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgSOU = ripser(arrayPoints)['dgms']
plot_diagrams(dgSOU, show=True, xy_range=[-100,1200,-100,1200])

"""#EVE - Everton - 16"""

eve = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/EVE.csv')
eve

arrayPoints = np.array(eve[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgEVE = ripser(arrayPoints)['dgms']
plot_diagrams(dgEVE, show=True, xy_range=[-100,1200,-100,1200])

"""#LEE - Leeds United - 17"""

lee = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/LEE.csv')
lee

arrayPoints = np.array(lee[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgLEE = ripser(arrayPoints)['dgms']
plot_diagrams(dgLEE, show=True, xy_range=[-100,1200,-100,1200])

"""#BRN - Burnley - 18"""

brn = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/BRN.csv')
brn

arrayPoints = np.array(brn[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgBRN = ripser(arrayPoints)['dgms']
plot_diagrams(dgBRN, show=True, xy_range=[-100,1200,-100,1200])

"""# WAT - Watford - 19"""

wat = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/WAT.csv')
wat

arrayPoints = np.array(wat[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgWAT = ripser(arrayPoints)['dgms']
plot_diagrams(dgWAT, show=True, xy_range=[-100,1200,-100,1200])

"""#NOR - Norwich City - 20"""

nor = pd.read_csv('https://raw.githubusercontent.com/wojtaskuba/Projekt_WamberskaWojtasZygmunt/main/Teams/NOR.csv')
nor

arrayPoints = np.array(nor[['POS','Mins','Goals','Shots','PenGoals','SuccesfulDribbles','Assists','AccPasses','KeyPasses','Fouls','WasFouled','YellowCards','RedCards','RecBalls','Tackles','CleanSheets']])
#arrayPoints

dgNOR = ripser(arrayPoints)['dgms']
plot_diagrams(dgNOR, show=True, xy_range=[-100,1200,-100,1200])
